#SPDX-License-Identifier: MIT-0
# tasks file for roles/firewall

---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    port: "22"

- name: Allow HTTP
  ufw:
    rule: allow
    port: "80"

- name: Allow HTTPS
  ufw:
    rule: allow
    port: "443"

- name: Enable UFW
  ufw:
    state: enabled
