#---
# SPDX-License-Identifier: MIT-0

galaxy_info:
  author: Maruf Salaudeen
  description: Common role for configuring Ubuntu web servers
  company: Personal Project
  license: MIT

  min_ansible_version: "2.16"

  galaxy_tags:
    - ubuntu
    - aws
    - nginx
    - ansible
    - devops

dependencies: []
